# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_q2 = torch.rand(7, 7)
tensor_q2

tensor([[0.5853, 0.1933, 0.9518, 0.5528, 0.1234, 0.7426, 0.2166],
        [0.4491, 0.0215, 0.4747, 0.8264, 0.5071, 0.8428, 0.8415],
        [0.4174, 0.0753, 0.5290, 0.1510, 0.4891, 0.6439, 0.6891],
        [0.3395, 0.9308, 0.0720, 0.3193, 0.6847, 0.6463, 0.5236],
        [0.8544, 0.9646, 0.0850, 0.3631, 0.9191, 0.8171, 0.8074],
        [0.2352, 0.2312, 0.3669, 0.5221, 0.3285, 0.6369, 0.1197],
        [0.5082, 0.3066, 0.0965, 0.3199, 0.6263, 0.7231, 0.8002]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor_q3 = torch.rand(1, 7)
# Perform matrix multiplication
tensor_q2 @ tensor_q3.T, tensor_q3 @ tensor_q2

(tensor([[1.3708],
         [1.1889],
         [0.8048],
         [0.8506],
         [1.2036],
         [0.8198],
         [0.7630]]),
 tensor([[1.0668, 0.8639, 1.0441, 0.9136, 1.1331, 1.6272, 1.3122]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
MM = tensor1 @ tensor2.T
MM, MM.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_A @ tensor_B.T, (tensor_A @ tensor_B.T).shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [26]:
AB_T = torch.mm(tensor_A, tensor_B.T)

### 8. Find the maximum and minimum values of the output of 7.

In [32]:
# Find max
AB_T.max(), AB_T.min()
# Find min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [33]:
# Find arg max
AB_T.argmax(), AB_T.argmin()

# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
